### PR TITLE
Feature/refactor to support answers api

### LINKED ISSUE #3: Initialisation failed + crash
Hi,
I'm trying to add the plugin to my project, but I'm facing several issues.
I don't really understand the plugin/framework init process. From my understanding of the fabric system, when the app is launch for the first time is should register / present itself to the backend (and appear under my organisation)
But I can't get my app registered on fabric.io.
Shouldn't the plugin call 
```
Fabric.with()
```
at some point ?

Another problem I have is when I use 
```
window.fabric.Answers.sendLogIn()
```

the app crash
```
E/AndroidRuntime(15212): FATAL EXCEPTION: main
E/AndroidRuntime(15212): Process: com.xxx.yyy, PID: 15212
E/AndroidRuntime(15212): java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
E/AndroidRuntime(15212): 	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:265)
E/AndroidRuntime(15212): 	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:516)
E/AndroidRuntime(15212): 	at com.crashlytics.android.answers.Answers.getInstance(Answers.java:45)
E/AndroidRuntime(15212): 	at com.sarriaroman.fabric.FabricPlugin$2.run(FabricPlugin.java:79)
E/AndroidRuntime(15212): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15212): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15212): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15212): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(15212): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15212): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15212): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(15212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

### LINKED ISSUE #4: Include libraries and update native projects on plugin install
We are using the [cordova-crashlytics-plugin](https://github.com/smistry-toushay/cordova-crashlytics-plugin.git) and are looking to upgrade to a newer plugin that uses the updated Fabric SDK.

There are two things this old plugin does that makes it really convenient to use.

1. It includes the Fabric SDK libraries with the plugin.
1. Uses an `after_plugin_install` build hook to modify the iOS and Android projects.

This makes it possible to use the plugin without checking in the platforms directory or doing any manual configuration steps. I would assume this would also take care of #2 as well.

### LINKED ISSUE #7: sendNonFatalCrash only sends the info to fabric.io after calling sendCrash
Hi, first of all, awesome plugin, I have been using it and is very good :)

Right now I have a request to log Non-Fatal Crashes, right now the sendNonFatalCrash function works but you have to call the sendCrash function after it in order for the app to actually send the info to Fabric.

So for example, if I do this:

window.fabric.Crashlytics.addLog('test 1');
window.fabric.Crashlytics.sendNonFatalCrash();
window.fabric.Crashlytics.addLog('test 2');
window.fabric.Crashlytics.sendNonFatalCrash();

and then I wait for and hour, there's no new Non-Fatal crashes reports in Fabric.
I have to call window.fabric.Crashlytics.sendCrash(); to actually see the Non-Fatal crashes in Fabric.

Thanks.
Robert

### LINKED ISSUE #8: Error using window.fabric.*
Hi, thanks for your work.

When I use your plugin as in your example I get `TypeError: undefined is not an object (evaluating 'window.fabric.Crashlytics')` in console.
I am using iPhone 5 with iOS 9.2, cordova 6.0.0, Crashlytics 3.6.0, Answers 1.1.0.

Edit : Well, I have more informations about this bug. I tested in chrome, everything is ok. When I test in safari 9 (used by iOS), logging `window` object, I find `fabric` as a sub-object that is not undefined. But logging `window.fabric` is undefined. I think the problem comes from the initialization of FabricPlugin variable.

    var FabricPlugin = (function () {
    function FabricPlugin() {
        _classCallCheck(this, FabricPlugin);
    }

    _createClass(FabricPlugin, [{
        key: 'pluginCallName',
        value: function pluginCallName() {
            return 'FabricPlugin';
        }
    }, {
        key: 'execPlugin',
        value: function execPlugin(method, parameters) {
            exec(null, null, this.pluginCallName(), method, [parameters]);
        }
    }]);

        return FabricPlugin;
    })();

    module.exports = new FabricPlugin();

Where you use FabricPlugin variable inside its declaration itself and return it. As it is initializing, FabricPlugin variable is not yet defined when returning it. Some browser may interpret it differently, and return different value. Or not... I don't know, I am not enough friend with javascript.

### LINKED ISSUE #9: Sending crash report crashes the app, how ironic :)
So, im sending a crash, nothing to fancy

````coffeescript
window.onerror = (message, source, lineno, colno, error) ->
  if fabric?
    console.log "Sending crash to Fabric.io"
    if CurrentUser? and CurrentUser.signedIn()
      fabric.Crashlytics.setUserIdentifier CurrentUser.get('id') 
      fabric.Crashlytics.setUserName CurrentUser.get('name')

    fabric.Crashlytics.addLog "#{message} | #{source} | #{lineno}:#{colno} | #{error}"
    fabric.Crashlytics.sendCrash()
````

than i get this error ( in crashlitcs so thats nice! )
````
Non-fatal Exception: java.lang.Throwable: Sending non fatal crash from JS
       at com.sarriaroman.fabric.FabricPlugin$6.run(FabricPlugin.java:158)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
````

### PR DESCRIPTION
**Pull request by Justin-Credible**
I believe this resolves #3, resolves #4, resolves #7, resolves #8, resolves #9.

### CODE REVIEW

**Comment by sarriaroman** [comment]
Amazing job. Thanks for your contribution!!

**Comment by Justin-Credible** [comment]
Would you mind publishing 1.0.0 to npm? Thanks!

**Comment by sarriaroman** [comment]
That's exactly what I'm working on. I'll let you know

**Comment by sarriaroman** [comment]
Done! https://www.npmjs.com/package/cordova-fabric-plugin

**Comment by Justin-Credible** [comment]
Excellent! Thanks!

**Pull request merged**
