### PR TITLE
Updated iOS SDK and changed bash script's relative path in workspace

### PR DESCRIPTION
**Pull request by onderceylan**
If you move generated iOS project workspace to another path, relative script path defined in project with the hook does not work anymore. Fixed that issue with scoping path within project workspace. Updated SDK as well.

### CODE REVIEW

**Comment by sarriaroman** [comment]
Hey @Justin-Credible can you review the PR just for Cross checking? Is ok for me.

**Comment by Justin-Credible** [comment]
The code change for the plugin path looks good to me.

As for the framework upgrade, it looks like Crashlytics takes a big jump from 3.6.x to 3.8.x. My only concern would be ensuring all existing functionality still works. Do we have a list of things that changed from 3.6 to 3.8 and how they affect the plugin?

**Comment by Justin-Credible** [comment]
I took at look at the Crashlytics SDK [changelog](https://docs.fabric.io/apple/changelog.html) and I don't see anything that worries me there. 👍

**Comment by onderceylan** [comment]
I also changed the script call from Crashlytics.framework/run to Fabric.framework/run as Fabric app guided me to do so.

**Comment by onderceylan** [comment]
I tested it with Crashlytics and it's working fine. I haven't tested Answers though.

**Comment by sarriaroman** [comment]
Merged and published to NPM

**Comment by onderceylan** [comment]
Great! Thanks 👍

**Pull request merged**
