### PR TITLE
Added support for Non Fatal Crashes on Android.

### PR DESCRIPTION
**Pull request by nbdamian**
I have added support for Non Fatal Crashed on Android.
I am not sure how to go about adding support for IOS.

### CODE REVIEW

**Comment by sarriaroman** [comment]
Please check the Line Endings because is giving me a 100% difference in files.

**Comment by nbdamian** [comment]
This should have resolved it. Blame Notepadqq's hidden files.

**Comment by sarriaroman** [comment]
The Java part is not required because it will be taken by the Reflection method. Just the Javascript part was missing and the right documentation. Please remove the IF and I will proceed to merge it.

**Comment by nbdamian** [comment]
This has been removed.

**Comment by sarriaroman** [comment]
I don't want to bother you again but for some reason your last commit is taking the entire Java as changed again :(. With that change I will be able to merge it.

**Comment by nbdamian** [comment]
Darn Ubuntu xD
It has been removed.

**Comment by sarriaroman** [comment]
Merged and released with v0.6.1

**Comment by tomsun** [comment]
Was curious, browsed to the history of this repo a bit...

Note that @nbdamian adds himself to authors in ec070bc94821a57aa52f9d40c7bf0888feb4724b but then removes himself again in the cleanup commit 2255836b33da938f11f224dd3662e307b0632ef1, probably unintentionally...

**Comment by nbdamian** [comment]
@tomsun With the little amount of code that I wrote, I didn't see it worth adding myself to authors.

**Comment by sarriaroman** [comment]
@nbdamian You can add yourself, you contributed to the improvement of the plugin! I'm glad of your help and for me it's ok if you add your name in the contributors list.

**Pull request merged**
